api cat
WildCodeSchool/2022-09-JS-Marseille-SNCF-P2-Trivial pull request #12
Opened 2022-12-16 15:15 UTC by jejem8430

2022-12-17 09:11 UTC, fredl2tp commented on react-trivial/src/Components/Footer.css
>      margin-left: 20%;
Les sélecteurs CSS doivent cibler des éléments précis de notre composant. Le nommage doit être sans équivoque. Chaque class ou ID doit faire référence au composant comme nous en avions convenu (fonction "-" nom du composant mais un nommage camelCase avec terminaison par le nom du composant peut suffire).

2022-12-17 09:14 UTC, fredl2tp requested changes
Les sélecteurs CSS doivent cibler des éléments précis de notre composant. Le nommage doit être sans équivoque. Chaque class ou ID doit faire référence au composant comme nous en avions convenu (fonction "-" nom du composant mais un nommage camelCase avec terminaison par le nom du composant peut suffire).

2022-12-17 11:07 UTC, Samikate requested changes
Pour suivre la demande de Frédéric, je me positionne sur "Demander des modifications". Je vais également reprendre mon nommage quant aux éléments. Bon week-end à vous deux et vive la France ⚽

2022-12-19 08:36 UTC, Samikate approved these changes

2022-12-19 08:36 UTC, fredl2tp approved these changes

2022-12-19 08:37 UTC, merged